In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from sklearn import linear_model

In [28]:
df = pd.read_csv("canada_per_capita_income.csv")
df.tail()

year  per capita income (US$)
42  2012              42665.25597
43  2013              42676.46837
44  2014              41039.89360
45  2015              35175.18898
46  2016              34229.19363

In [16]:
# Find X and Y 
X= df[['year']]
Y = df[['per capita income (US$)']]


In [22]:
regModel = linear_model.LinearRegression()
regModel.fit(X,Y)
#regModel.fit(df[['year']], df[['per capita income (US$)']])
regModel.coef_
regModel.intercept_

array([-1632210.75785546])

In [23]:
regModel.fit(df[['year']], df[['per capita income (US$)']])
regModel.coef_
regModel.intercept_

array([-1632210.75785546])

In [29]:
regModel.predict([[2017]])

array([[38803.29886875]])